### ISSUE TITLE
Change GuzzleAdapter cofguration merging funcionality 

### ISSUE THREAD

**Issue by jurajpitak** [profesia/service-layer#1]
I found a issue while merging configuration in Guzzle adapter. It can be risky
https://github.com/profesia/service-layer/blob/e792fa190f916ada5de9d7251704ad922807cf53/src/Adapter/GuzzleAdapter.php#L44

Current: 
```
$finalConfig = array_merge(
                $finalConfig,
                [
                    RequestOptions::HEADERS => $psrRequest->getHeaders(),
                ]
            );
```

Expected:
```
$finalConfig = array_merge(
                $finalConfig,
                [
                    RequestOptions::HEADERS => array_merge(
                    $finalConfig[RequestOptions::HEADERS] ?? [],
                        $psrRequest->getHeaders(),
                    )
                ]
            );
```

I try define headers in symfony services and after merging configuration with this code are headers cleared.

**Comment by mbadal** [comment]
Implemented in: https://github.com/profesia/service-layer/releases/tag/v1.3.0 .
